version: '3.10'
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./config/secrets.yml
    environment:
      - MONGODB_URL=${MONGODB_DATABASE}
  tests:
    build: .
    command: python -m pytest
    depends_on:
      - app