name: Flow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: coverage report --fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/html

      - name: Build and package application
        run: |
          # Add your build commands here

          # Check coverage percentage
          COVERAGE_PERCENTAGE=$(coverage report --fail-under=80 --show-missing | tail -n 1 | awk '{print $NF}' | tr -d '%')
          echo "Coverage Percentage: $COVERAGE_PERCENTAGE%"

          # Check if coverage is 80% or higher
          if [ $COVERAGE_PERCENTAGE -ge 80 ]; then
            # Increase package version
            CURRENT_VERSION=$(cat version.txt)
            NEW_VERSION=$(python -c "parts = '$CURRENT_VERSION'.split('.'); parts[-1] = str(int(parts[-1]) + 1); print('.'.join(parts))")
            echo "New Package Version: $NEW_VERSION"

            # Build new package with increased version
            # Add your build commands specific to packaging with the new version

            # Update version.txt file with the new version
            echo "$NEW_VERSION" > version.txt
          else
            echo "Coverage is below 80%. Skipping package creation and version increase."
          fi
