name: Flow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create virtual environment
        run: python -m venv venv
  
      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: coverage report --fail-under=80

      - name: Install wheel package
        run: pip install wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist

      - name: Publish package to GitHub Packages
        run: |
          python -m pip install --upgrade twine
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TOKEN }}
