name: Build, Test, and Publish Docker Image to Amazon ECR 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGISTRY: "822546254290.dkr.ecr.us-west-1.amazonaws.com"
  ECR_REPOSITORY: "taskproject"
  AWS_REGION: "us-west-1"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code repository 
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create virtual environment for Python
        run: python -m venv venv

      - name: Activate virtual environment for Python
        run: source venv/bin/activate

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies for Python
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report and fail if coverage is below 80%
        run: coverage report --fail-under=80

      - name: Install Docker CLI
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials for Docker 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Docker login to Amazon ECR registry
        run: aws ecr get-login-password --region ${{env.AWS_REGION}} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}

      - name: Build Docker image and tag with latest tag
        run: docker build --file Dockerfile --tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image with commit hash 
        run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker image with latest tag to Amazon ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Upload package to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist
      