name: Build, Test, and Publish Docker Image to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGISTRY: "822546254290.dkr.ecr.us-west-1.amazonaws.com"
  ECR_REPOSITORY: "taskproject"
  AWS_REGION: "us-west-1"
  SONAR_PROJECT_KEY: "TaskProject"

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'   

  Linting-node:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Move to client directory
      #   run: cd client

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./client

      - name: Analysing the code with eslint
        run: |
          npm install eslint
          npx eslint $(git ls-files '*.js')
        working-directory: ./client

      - name: Analysing the code with stylelint
        run: |
          npm install stylelint
          npm install --save-dev stylelint-config-standard
          npx stylelint $(git ls-files '*.css')
        working-directory: ./client

      - name: Analysing the code with prettier
        run: |
          npm install prettier
          npx prettier --write $(git ls-files '*.js')
          npx prettier --check $(git ls-files '*.js')
        working-directory: ./client

      # - name: Lint Code Base
      #   uses: github/super-linter@v5
      #   env:
      #     VALIDATE_JAVASCRIPT_ES: true
      #     VALIDATE_JAVASCRIPT_STANDARD: true
      #     VALIDATE_CSS_ES: true
      #     VALIDATE_CSS_STANDARD: true

  Linting-python:
    runs-on: ubuntu-latest
    needs: [setup-python]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Analysing the code with black
        run: |
          pip install black
          black .
          black --check $(git ls-files '*.py')

      # - name: Analysing the code with pylint
      #   run: |
      #     pip install pylint
      #     pylint $(git ls-files '*.py')
      #     pylint --exit-zero

      - name: Analysing the code with flake8
        run: |
          pip install flake8
          flake8 $(git ls-files '*.py')

      # - name: Lint Code Base
      #   uses: github/super-linter@v5
      #   env:
      #     VALIDATE_PYTHON_BLACK: true
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing-backend:
    runs-on: ubuntu-latest
    needs: [setup-python , Linting-python]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Run tests with coverage
        run: coverage run --source . --omit '/usr/*' -m pytest
  
      - name: Generate coverage report and fail if coverage is below 80%
        run: coverage report --fail-under=80
  
      - name: Generate coverage report in XML format
        run: coverage xml -o coverage.xml --omit=venv/*,tests/*

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: [Linting-node]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./client

      - name: Build client
        run: |
          npm run build
        working-directory: ./client
        
      - name: Test client
        run: |
          npm run test -- --passWithNoTests
        working-directory: ./client

  sonarQube-scan:
    needs: [testing-backend, build-and-test-frontend] 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.python.coverage.reportPaths=coverage.xml

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #     SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}

      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-publish:
    needs: [testing-backend, sonarQube-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
          
      - name: Install Docker CLI
        uses: docker/setup-buildx-action@v2
      

      - name: Configure AWS credentials for Docker
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  

      - name: Docker login to Amazon ECR registry
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.TOKEN }}
        
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}


      # - name: Delete old ECR image
      #   run: |
      #     aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --query 'imageDetails[].imageDigest' --output text | while read -r line; do aws ecr batch-delete-image --repository-name ${{ env.ECR_REPOSITORY }} --image-ids imageDigest="$line"; done

      - name: Build Docker image and tag with latest tag
        run: |
          docker build --file Dockerfile --tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }} .

      - name: Tag Docker image with commit hash
        run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }}

      - name: Push Docker image with latest tag to Amazon ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }}

      - name: Push Docker image with commit hash tag to Amazon ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }}

