name: Flow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: coverage report --fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/html

      - name: Build and package application
        run: |
          python maion.py sdist bdist_wheel

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist

      