name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          COVERAGE_PERCENTAGE=$(coverage report | grep TOTAL | awk '{print $NF}' | tr -d '%')

          if [ $COVERAGE_PERCENTAGE -gt 80 ]; then
            echo "Coverage is above 80%. Creating package with increased version number."
            CURRENT_VERSION=$(cat version.txt)
            VERSION_PARTS=(${CURRENT_VERSION//./ })
            NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((${VERSION_PARTS[2]} + 1))"
            echo "New Package Version: $NEW_VERSION"

            # Update version.txt file with the new version
            echo "$NEW_VERSION" > version.txt

            # Build the package
            python setup.py sdist bdist_wheel
          else
            echo "Coverage is below 80%. Skipping package creation."
          fi
